- .githooks/pre-commit
missing githooks from the archived repo
> add githooks

- src/controllers/other/reason.other.controller.ts
- views/check-your-answers.html
- views/error.html
- views/other/reason-other.html
Also corrected error links, data retention upon errors and corrected back button on error page.
> Added change link for other reason on check answers page

- package-lock.json
Updating handlebars package as highlighted by the npm vulnerability audit
> npm vulnerability fix

- views/index.html
> Added new link to start screen

- src/controllers/confirmation.controller.ts
Was causing the confirmation page to render without auth code journey text when coming from the printer friendly page using back button
> Moved auth code feature check out of isSubmitted check on confirmation page

- src/controllers/confirmation.controller.ts
Needed to be inside conditional js npe caused failure.
> lfa-1173 unit test fix

- package-lock.json
- views/company-number.html
- views/layout.html
Also fixed the survey link to open in a new tab for LFA-1396
> Removed data-event-id on help with company number link 

- package-lock.json
- src/controllers/company.number.controller.ts
- src/controllers/too.soon.controller.ts
- src/model/page.urls.ts
- src/model/template.paths.ts
- src/routes/routes.ts
- src/test/controllers/company.details.controller.spec.unit.ts
- src/test/controllers/company.number.controller.spec.unit.ts
- src/test/controllers/too.soon.controller.spec.unit.ts
- src/test/global.setup.ts
- views/too-soon.html
If customer is applying for an extension greater than the number of days in the config before their due date, then they will get the Too soon to apply screen.
Depends on config - https://github.com/companieshouse/chs-configs/pull/963
> LFA-1519 Adding Too Soon to apply screen

- views/confirmation.html
Updated the "what happens next" section to match what is specified on the screenshot - not updated any other text on this screen.
> COVID-19 text

- src/client/apiclient.ts
- views/too-soon.html
changing \<b> to \<strong> on Too Soon screen an removing an unnecessary cast
> Sonar fix bugs for html tag and unnecessary cast

- package-lock.json
- package.json
- views/index.html
Jira ticket at https://companieshouse.atlassian.net/browse/LFA-1685
> Added beta banner and ran audit fix

- views/extension-limit-reached.html
Jira ticket at https://companieshouse.atlassian.net/browse/LFA-1928
> LFA-1928 renaming error page and adding monthLimit variable to replace hardcoded numbers

- package-lock.json
- src/client/apiclient.ts
- src/model/extension.request.status.ts
- src/test/client/apiclient.set.extension.status.spec.unit.ts
- src/test/client/apiclient.spec.integration.ts
- src/test/mockserver/company/00006400/extensions/requests/5cc84e5e1e8ff21f5863c22d/PATCH.mock
Adding new function to allow us to call PATCh on the extensions-api to set the extensions status for rejecting when exceeding extension period.
> LFA-1925 Adding api client set extension request status function

- src/app.ts
- views/layout.html
> OBJ-416 Favicon required

- package-lock.json
- package.json
> resolve known vulnerabilities

- Dockerfile
- Tiltfile.dev
> OBJ-492 jib and tiltfile added

- views/extension-limit-reached.html
- views/index.html
- views/layout.html
Added no referer to hyperlinks with http/s urls.
> BI-8262 Added no referer to prevent attacks

- src/controllers/accounts/accounts.date.controller.ts
- src/controllers/illness/illness.end.date.controller.ts
- src/controllers/illness/illness.start.date.controller.ts
- src/controllers/other/reason.other.controller.ts
Removed extra parentheses from four switch statements.
> BI-8263 Remove Parentheses

- src/controllers/company.number.controller.ts
Regex update to what we have in objections web.
> BI-8265 Company number regex is unsafe

- views/layout.html
> BI-4952 JQuery update

- package-lock.json
- package.json
Upgrading axios to 0.21.4 recommended by the 'npm audit' process after running 'npm audit fix'
> BI-10420 Upgrade axios to 0.21.4

- src/controllers/illness/illness.start.date.controller.ts
Fixing a lint error - trailing whitespace
> BI-10420 Fix trailing whitespace lint error

- src/authentication/middleware/index.ts
- src/controllers/healthcheck.controller.ts
- src/model/page.urls.ts
- src/routes/routes.ts
- src/session/middleware/history.ts
- src/test/controllers/healthcheck.controller.spec.unit.ts
https://companieshouse.atlassian.net/browse/CC-627
Adding a new /healthcheck endpoint needed by the new ECS pipeline for extensions-web
> CC-627 Add healthcheck endpoint

- Dockerfile
- package-lock.json
- package.json
- src/client/apiclient.ts
- src/controllers/accounts/accounts.date.controller.ts
- src/controllers/accounts/accounts.information.controller.ts
- src/controllers/document.upload.controller.ts
- src/controllers/illness/continued.illness.controller.ts
- src/controllers/illness/illness.end.date.controller.ts
- src/controllers/illness/illness.information.controller.ts
- src/controllers/illness/illness.start.date.controller.ts
- src/controllers/illness/who.was.ill.controller.ts
- src/controllers/other/reason.other.controller.ts
- src/controllers/remove.document.controller.ts
- src/controllers/remove.reason.controller.ts
- src/session/middleware/session.query.ts
- src/test/client/apiclient.spec.unit.ts
- src/test/session/session.query.spec.unit.ts
CC-622 merge to CC-472 changes to Dockerfile, package.json, package-lock.json and test files
> Node 18 package updates

- Makefile
JIRA link
https://companieshouse.atlassian.net/browse/CC-647
Description
edit test-unit to run npm run sonar-test
> CC-647 edit test-unit to run npm run sonar-test

- terraform/groups/ecs-services/vault-providers/approle
- terraform/groups/ecs-services/vault-providers/token
- terraform/groups/ecs-services/vault-providers/userpass
JIRA Link
https://companieshouse.atlassian.net/browse/CC-651
Description
Create vault-providers folder and files
> cc-651 Create vault-providers folder and files

- terraform/groups/ecs-service/data.tf
- terraform/groups/ecs-service/locals.tf
- terraform/groups/ecs-service/main.tf
- terraform/groups/ecs-service/variables.tf
https://companieshouse.atlassian.net/browse/CC-559
Updating terraform resources and git sources
> CC-559 Update terraform resources

- terraform/groups/ecs-service/main.tf
https://companieshouse.atlassian.net/browse/CC-559
Adding missing use_fargate var
> CC-559 Add missing use_fargate variable

- Makefile
https://companieshouse.atlassian.net/browse/CC-559
Adding security-check to makefile for new pipeline to call
> CC-559 Adding securit-check to makefile

- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
https://companieshouse.atlassian.net/browse/CC-686
* LIVE config added
* Minor change to Staging config so that CDN Host definition now correct (matches format in CiDev)
> CC-686 Added LIVE Terraform config vars

- package-lock.json
- package.json
Resolves high/critical vulnerabilities in service
> Feature/CC-1158: Resolve dependency vulnerabilities

- package-lock.json
- package.json
JIRA link
https://companieshouse.atlassian.net/browse/SEC-108
Change description
add @companieshouse/web-security-node dependency
> feature : add @companieshouse/web-security-node dependency

- views/accessibility-statement.html
- Updated accessibility statement.
> update accessibility statement

- README.md
- package-lock.json
- package.json
- sonar-project.properties
https://companieshouse.atlassian.net/browse/ASM-507
update the sonar dependency to run with the new pipeline version of sonar
> ASM-507 Upgrade Sonar dependency version

- package-lock.json
JIRA link
https://companieshouse.atlassian.net/browse/ASM-603
Change description
fix dependencies vulnerability
> asm-603 : run audit fix
